# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-06-23 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20180623_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ingredients',
            field=models.ManyToManyField(related_name='items', to='menu.Ingredient'),
        ),
    ]
